### ISSUE TITLE
Verificação de tamanho/formato não funciona correto

### ISSUE THREAD

**Issue by danielmessi13** [diaspa-nds/cfar#99]
Quando adiciono um professor tenho que inserir uma Siape/Matricula que contenha somente 7 números. Quando eu passo algo que contem menos números ele não aceita, mas se eu inserir algo com mais de 7 números.

O mesmo acontece quando adiciono um local no momento de inserir o código do local.

**Comment by danieldsf** [comment]
@danielmessi13 Realmente, não cabe ao sistema fazer esse tipo de validação, sendo que as regras podem mudar. Foi sugerida uma mudança para tornar isso mais liberal.
